$(NAME) : 
	@cd pidoux_q/ncurses/ && $(MAKE)
	@cd pidoux_q/SFML/ && $(MAKE)


all	: 
	@cd pidoux_q/ncurses/ && $(MAKE)
	@cd pidoux_q/SFML/ && $(MAKE)

clean	:
	@cd pidoux_q/ncurses/ && $(MAKE) clean
	@cd pidoux_q/SFML/ && $(MAKE) clean

fclean	:
	@cd pidoux_q/ncurses/ && $(MAKE) fclean
	@cd pidoux_q/SFML/ && $(MAKE) fclean

re	:
	@cd pidoux_q/ncurses/ && $(MAKE) re
	@cd pidoux_q/SFML/ && $(MAKE) re