#ifndef __DIRECTIVESORDER_H__
# define __DIRECTIVESORDER_H__

enum DirectivesOrder
{
	CONNECTION_INIT = 1,
	PREPROCESS_REQUEST = 2,
	PROCESS_REQUEST = 4,
	CREATE_RESPONSE = 8,
	PROCESS_FINISHED_RESPONSE = 16,
	PRESENDING_PROCESSING = 32,
	CONNECTION_CLOSED = 64
};


#endif // !__DIRECTIVESORDER_H__
